-- AUTO-GENERATED by scripts/build-seed.mjs from lib/mock-data.ts.
-- Re-run `node scripts/build-seed.mjs` after editing the mock.

insert into public.cockpit_snapshot (snapshot_date, payload) values
('2026-05-22', $${
  "today": "2026-05-22",
  "hero": {
    "status": "conforme",
    "statusLabel": "Conforme",
    "current_kg": 83.9,
    "ideal_kg": 83.6,
    "delta_kg": 0.3,
    "tolerance_kg": 0.8,
    "start_date": "2026-04-14",
    "today_week": 5.4,
    "range": {
      "kg_min": 75,
      "kg_max": 87,
      "week_min": 0,
      "week_max": 52
    },
    "real_points": [
      {
        "week": 0,
        "kg": 86.3
      },
      {
        "week": 1,
        "kg": 85.9
      },
      {
        "week": 2,
        "kg": 85.5
      },
      {
        "week": 3,
        "kg": 85.3
      },
      {
        "week": 4,
        "kg": 85
      },
      {
        "week": 4.7,
        "kg": 84.4
      },
      {
        "week": 5,
        "kg": 84.3
      },
      {
        "week": 5.4,
        "kg": 83.9
      }
    ],
    "eta_75kg": "2027-02-18"
  },
  "wegovy": {
    "day_since_start": 38,
    "current_dose_mg": 0.5,
    "step_index": 2,
    "ladder": [
      {
        "dose_mg": 0.25,
        "status": "done"
      },
      {
        "dose_mg": 0.5,
        "status": "current"
      },
      {
        "dose_mg": 1,
        "status": "upcoming"
      },
      {
        "dose_mg": 1.7,
        "status": "upcoming"
      },
      {
        "dose_mg": 2.4,
        "status": "upcoming"
      }
    ],
    "next_dose_mg": 1,
    "next_in_weeks": 2
  },
  "signals": [
    {
      "id": "tdee",
      "title": "TDEE apparent",
      "sub": "28 j · coeff 6 500 (Wegovy) · biais log ~20 %",
      "value": "2 270",
      "unit": "± 180 kcal",
      "status": "ok",
      "status_label": "on track",
      "spark": {
        "kind": "line",
        "color": "sage",
        "points": [
          [
            2,
            14
          ],
          [
            14,
            16
          ],
          [
            26,
            12
          ],
          [
            38,
            14
          ],
          [
            50,
            11
          ],
          [
            62,
            13
          ],
          [
            78,
            12
          ]
        ]
      }
    },
    {
      "id": "protein",
      "title": "Protéines / LBM",
      "sub": "zone adéquate 2,0–2,4 · jours train −0,3 = risque sarcopénie",
      "value": "1,9",
      "unit": "g/kg LBM",
      "status": "watch",
      "status_label": "à surveiller",
      "spark": {
        "kind": "bars",
        "color": "ambre",
        "values": [
          16,
          18,
          8,
          17,
          19,
          9,
          16,
          18,
          10,
          17,
          19,
          9,
          17
        ],
        "dim_indices": [
          2,
          5,
          8,
          11
        ]
      }
    },
    {
      "id": "alcohol",
      "title": "Alcool",
      "sub": "CCSA 2023 · zone ambre 7–14 u/sem · stable vs baseline 84 j",
      "value": "9",
      "unit": "u/sem",
      "status": "watch",
      "status_label": "zone ambre",
      "spark": {
        "kind": "line",
        "color": "ambre",
        "points": [
          [
            2,
            12
          ],
          [
            14,
            14
          ],
          [
            26,
            11
          ],
          [
            38,
            13
          ],
          [
            50,
            12
          ],
          [
            62,
            13
          ],
          [
            78,
            12
          ]
        ]
      }
    },
    {
      "id": "sleep_hrv",
      "title": "Dette sommeil × HRV",
      "sub": "z = −1,2 vs perso 28 j · HRV PPG trend only",
      "value": "−3 h 20",
      "unit": "/ 7 j",
      "status": "watch",
      "status_label": "à surveiller",
      "spark": {
        "kind": "line",
        "color": "ambre",
        "points": [
          [
            2,
            8
          ],
          [
            14,
            10
          ],
          [
            26,
            12
          ],
          [
            38,
            13
          ],
          [
            50,
            15
          ],
          [
            62,
            17
          ],
          [
            78,
            18
          ]
        ]
      }
    },
    {
      "id": "wegovy_response",
      "title": "Réponse Wegovy",
      "sub": "−2,4 kg réel vs −2,2 prédit STEP-1 W5,4 · z = +0,1",
      "value": "+0,1",
      "unit": "z STEP-1",
      "status": "ok",
      "status_label": "sur trajectoire",
      "spark": {
        "kind": "line",
        "color": "sage",
        "end_dot": true,
        "points": [
          [
            2,
            18
          ],
          [
            14,
            17
          ],
          [
            26,
            15
          ],
          [
            38,
            13
          ],
          [
            50,
            11
          ],
          [
            62,
            9
          ],
          [
            78,
            7
          ]
        ]
      }
    }
  ],
  "bio_age": {
    "composite": 33,
    "chrono": 35,
    "delta_vs_chrono": -2,
    "subages": [
      {
        "key": "cardio",
        "label": "Cardio",
        "value": 28
      },
      {
        "key": "blood",
        "label": "Sang",
        "value": 34
      },
      {
        "key": "composition",
        "label": "Composition",
        "value": 36
      },
      {
        "key": "skeleton",
        "label": "Squelette",
        "value": 36
      }
    ],
    "trajectory_12m": [
      {
        "month": "MAI '25",
        "value": 36
      },
      {
        "month": "JUIL",
        "value": 35.7
      },
      {
        "month": "SEPT",
        "value": 35.2
      },
      {
        "month": "NOV",
        "value": 35
      },
      {
        "month": "JAN",
        "value": 34.5
      },
      {
        "month": "MAR",
        "value": 34
      },
      {
        "month": "MAI '26",
        "value": 33
      }
    ]
  },
  "pillars": [
    {
      "key": "composition",
      "label": "Composition",
      "meta": "21 avr",
      "figure": "24,3",
      "unit": "% MG",
      "chart": {
        "kind": "area",
        "target_label": "cible 16",
        "target_y": 72,
        "points": [
          [
            8,
            12
          ],
          [
            50,
            22
          ],
          [
            92,
            36
          ],
          [
            134,
            48
          ],
          [
            176,
            56
          ],
          [
            192,
            60
          ]
        ]
      }
    },
    {
      "key": "activity",
      "label": "Activité",
      "meta": "auj.",
      "figure": "8 247",
      "unit": "pas",
      "chart": {
        "kind": "bars",
        "target_label": "10 k",
        "target_y": 18,
        "values": [
          56,
          64,
          46,
          66,
          40,
          58,
          44
        ],
        "dim_indices": [
          4,
          6
        ]
      }
    },
    {
      "key": "cardio",
      "label": "Cardio",
      "meta": "12 sem",
      "figure": "46",
      "unit": "ml/kg",
      "chart": {
        "kind": "area",
        "target_label": "cible 55",
        "target_y": 10,
        "points": [
          [
            8,
            60
          ],
          [
            38,
            56
          ],
          [
            68,
            48
          ],
          [
            98,
            40
          ],
          [
            128,
            32
          ],
          [
            158,
            26
          ],
          [
            192,
            22
          ]
        ]
      }
    },
    {
      "key": "recovery",
      "label": "Récupération",
      "meta": "7 j",
      "figure": "6 h 42",
      "unit": "moy.",
      "chart": {
        "kind": "bars",
        "target_band": {
          "y": 14,
          "h": 14
        },
        "values": [
          36,
          48,
          28,
          52,
          40,
          32,
          40
        ],
        "ambre_indices": [
          0,
          2,
          4,
          5,
          6
        ]
      }
    }
  ],
  "pillar_detail": {
    "composition": {
      "key": "composition",
      "title": "Composition corporelle",
      "meta": "Withings · dernière mesure 21 avr 2026",
      "hero": {
        "figure": "24,3",
        "unit": "% MG",
        "delta_label": "−4,2 pts vs novembre 2025",
        "status_label": "Dérive mineure",
        "status_off": true
      },
      "trajectory": {
        "x_label": "12 mois",
        "y_unit": "% MG",
        "y_min": 14,
        "y_max": 30,
        "points": [
          {
            "date": "JUIN '25",
            "value": 28.5
          },
          {
            "date": "JUIL",
            "value": 28.3
          },
          {
            "date": "AOÛT",
            "value": 28
          },
          {
            "date": "SEPT",
            "value": 27.6
          },
          {
            "date": "OCT",
            "value": 27.2
          },
          {
            "date": "NOV",
            "value": 27
          },
          {
            "date": "DÉC",
            "value": 26.7
          },
          {
            "date": "JANV '26",
            "value": 26.4
          },
          {
            "date": "FÉVR",
            "value": 25.8
          },
          {
            "date": "MARS",
            "value": 25.1
          },
          {
            "date": "AVR",
            "value": 24.3
          },
          {
            "date": "MAI '26",
            "value": 24.3
          }
        ],
        "target": {
          "value": 16,
          "label": "cible 16 %"
        }
      },
      "table": [
        {
          "date": "21 avr 2026",
          "value": "24,3",
          "unit": "% MG",
          "delta": "−0,8"
        },
        {
          "date": "24 mars 2026",
          "value": "25,1",
          "unit": "% MG",
          "delta": "−0,7"
        },
        {
          "date": "22 févr 2026",
          "value": "25,8",
          "unit": "% MG",
          "delta": "−0,6"
        },
        {
          "date": "25 janv 2026",
          "value": "26,4",
          "unit": "% MG",
          "delta": "−0,3"
        },
        {
          "date": "28 déc 2025",
          "value": "27,0",
          "unit": "% MG",
          "delta": "−0,2"
        },
        {
          "date": "23 nov 2025",
          "value": "27,6",
          "unit": "% MG",
          "delta": "−0,2"
        }
      ],
      "method": [
        {
          "heading": "Source",
          "body": "Withings Body Scan, impédancemétrie segmentaire 8 électrodes à 50 kHz. Mesure une fois par semaine au lever, à jeun, vessie vide. Le MG % est calculé par l'équation propriétaire Withings, calibrée sur l'hydratation et la masse non grasse segmentaire (bras, tronc, jambes)."
        },
        {
          "heading": "Fenêtre & lissage",
          "body": "Affichage = moyenne mobile sur 4 mesures, pour atténuer le bruit BIA jour à jour (typiquement ± 0,8 pt selon l'hydratation et le contenu digestif). La trajectoire couvre les 12 derniers mois afin de lire la tendance, pas le point isolé."
        },
        {
          "heading": "Seuils & cible",
          "body": "Cible long terme 16 % MG, catégorie « athletic » ACSM pour la cohorte 30-39 ans. Bande conforme ± 1,5 pt autour de la trajectoire idéale Gompertz, dérivée du modèle poids global (75 kg propre). En parallèle, viser VAT < 100 cm² (seuil Withings de risque cardiométabolique)."
        }
      ],
      "cross_link": {
        "label": "Voir signal TDEE apparent",
        "href": "/#tdee"
      }
    },
    "activity": {
      "key": "activity",
      "title": "Activité quotidienne",
      "meta": "Huawei Watch GT2 · aujourd'hui 13 h 22",
      "hero": {
        "figure": "8 247",
        "unit": "pas aujourd'hui",
        "delta_label": "moyenne 7 j: 8 940 / 10 000",
        "status_label": "Dérive mineure",
        "status_off": true
      },
      "trajectory": {
        "x_label": "30 jours",
        "y_unit": "pas",
        "y_min": 4000,
        "y_max": 14000,
        "points": [
          {
            "date": "23 avr",
            "value": 9120
          },
          {
            "date": "24 avr",
            "value": 10450
          },
          {
            "date": "25 avr",
            "value": 6210
          },
          {
            "date": "26 avr",
            "value": 5780
          },
          {
            "date": "27 avr",
            "value": 11020
          },
          {
            "date": "28 avr",
            "value": 10380
          },
          {
            "date": "29 avr",
            "value": 9640
          },
          {
            "date": "30 avr",
            "value": 11890
          },
          {
            "date": "1 mai",
            "value": 8740
          },
          {
            "date": "2 mai",
            "value": 6320
          },
          {
            "date": "3 mai",
            "value": 5910
          },
          {
            "date": "4 mai",
            "value": 10240
          },
          {
            "date": "5 mai",
            "value": 12800
          },
          {
            "date": "6 mai",
            "value": 11430
          },
          {
            "date": "7 mai",
            "value": 9680
          },
          {
            "date": "8 mai",
            "value": 10110
          },
          {
            "date": "9 mai",
            "value": 5640
          },
          {
            "date": "10 mai",
            "value": 6080
          },
          {
            "date": "11 mai",
            "value": 9920
          },
          {
            "date": "12 mai",
            "value": 10780
          },
          {
            "date": "13 mai",
            "value": 8410
          },
          {
            "date": "14 mai",
            "value": 11260
          },
          {
            "date": "15 mai",
            "value": 9340
          },
          {
            "date": "16 mai",
            "value": 8980
          },
          {
            "date": "17 mai",
            "value": 5908
          },
          {
            "date": "18 mai",
            "value": 10602
          },
          {
            "date": "19 mai",
            "value": 11240
          },
          {
            "date": "20 mai",
            "value": 7480
          },
          {
            "date": "21 mai",
            "value": 9112
          },
          {
            "date": "22 mai",
            "value": 8247
          }
        ],
        "target": {
          "value": 10000,
          "label": "cible 10 k"
        }
      },
      "table": [
        {
          "date": "ven 22 mai",
          "value": 8247,
          "unit": "pas",
          "delta": "−865"
        },
        {
          "date": "jeu 21 mai",
          "value": 9112,
          "unit": "pas",
          "delta": "+1 632"
        },
        {
          "date": "mer 20 mai",
          "value": 7480,
          "unit": "pas",
          "delta": "−3 760"
        },
        {
          "date": "mar 19 mai",
          "value": 11240,
          "unit": "pas",
          "delta": "+638"
        },
        {
          "date": "lun 18 mai",
          "value": 10602,
          "unit": "pas",
          "delta": "+4 694"
        },
        {
          "date": "dim 17 mai",
          "value": 5908,
          "unit": "pas",
          "delta": "−3 072",
          "off": true
        },
        {
          "date": "sam 16 mai",
          "value": 8980,
          "unit": "pas",
          "delta": "+1 500"
        }
      ],
      "method": [
        {
          "heading": "Source",
          "body": "Huawei Watch GT2, podomètre 3 axes couplé au capteur de fréquence cardiaque pour détecter les minutes actives. Synchronisation Huawei Health une fois par jour. Comptage des pas à partir de 00:00 heure locale Dubaï."
        },
        {
          "heading": "Cible 10 000 pas",
          "body": "Heuristique grand public, originellement issue d'une campagne marketing Yamasa (Japon, 1965) et popularisée par les travaux de Tudor-Locke à partir de 2011. Ce n'est pas un consensus médical strict. La corrélation avec la mortalité toutes causes est documentée (Saint-Maurice, JAMA 2020) avec un plateau de bénéfice situé entre 8 000 et 12 000 pas par jour chez les adultes de moins de 60 ans."
        },
        {
          "heading": "Fenêtre & seuils",
          "body": "Moyenne mobile sur 7 jours pour lisser l'effet weekend. Dérive mineure si la moyenne 7 j passe sous 9 000 pas. Dérive notable sous 7 500 pas. Affichage sur 30 jours pour repérer les rebonds et les phases creuses."
        }
      ],
      "cross_link": {
        "label": "Voir signal TDEE apparent",
        "href": "/#tdee"
      }
    },
    "cardio": {
      "key": "cardio",
      "title": "Cardio",
      "meta": "Huawei Watch GT2 · estimation Firstbeat",
      "hero": {
        "figure": "46",
        "unit": "ml/kg/min",
        "delta_label": "+5 vs février 2026 (3 mois)",
        "status_label": "Conforme",
        "status_off": false
      },
      "trajectory": {
        "x_label": "12 semaines",
        "y_unit": "ml/kg/min",
        "y_min": 38,
        "y_max": 58,
        "points": [
          {
            "date": "26 fév",
            "value": 41
          },
          {
            "date": "5 mars",
            "value": 41
          },
          {
            "date": "12 mars",
            "value": 42
          },
          {
            "date": "19 mars",
            "value": 42
          },
          {
            "date": "26 mars",
            "value": 43
          },
          {
            "date": "2 avr",
            "value": 43
          },
          {
            "date": "9 avr",
            "value": 44
          },
          {
            "date": "16 avr",
            "value": 44
          },
          {
            "date": "23 avr",
            "value": 45
          },
          {
            "date": "30 avr",
            "value": 45
          },
          {
            "date": "7 mai",
            "value": 46
          },
          {
            "date": "21 mai",
            "value": 46
          }
        ],
        "ideal": [
          {
            "date": "26 fév",
            "value": 42
          },
          {
            "date": "5 mars",
            "value": 42.7
          },
          {
            "date": "12 mars",
            "value": 43.5
          },
          {
            "date": "19 mars",
            "value": 44.2
          },
          {
            "date": "26 mars",
            "value": 44.9
          },
          {
            "date": "2 avr",
            "value": 45.6
          },
          {
            "date": "9 avr",
            "value": 46.4
          },
          {
            "date": "16 avr",
            "value": 47.1
          },
          {
            "date": "23 avr",
            "value": 47.8
          },
          {
            "date": "30 avr",
            "value": 48.5
          },
          {
            "date": "7 mai",
            "value": 49.3
          },
          {
            "date": "21 mai",
            "value": 50
          }
        ],
        "target": {
          "value": 55,
          "label": "cible 55 (top 5-10 % cohorte 35-40)"
        },
        "tolerance": 2
      },
      "table": [
        {
          "date": "21 mai 2026",
          "value": "46",
          "unit": "ml/kg",
          "delta": "+1"
        },
        {
          "date": "14 mai 2026",
          "value": "45",
          "unit": "ml/kg",
          "delta": "+0"
        },
        {
          "date": "7 mai 2026",
          "value": "45",
          "unit": "ml/kg",
          "delta": "+1"
        },
        {
          "date": "30 avr 2026",
          "value": "44",
          "unit": "ml/kg",
          "delta": "+0"
        },
        {
          "date": "23 avr 2026",
          "value": "44",
          "unit": "ml/kg",
          "delta": "+1"
        },
        {
          "date": "16 avr 2026",
          "value": "43",
          "unit": "ml/kg",
          "delta": "+1"
        }
      ],
      "subs": [
        {
          "key": "hr_rest",
          "label": "HR repos 90 j",
          "unit": "bpm",
          "current": "54",
          "trend_label": "−4 / 90 j",
          "points": [
            {
              "date": "20 fév",
              "value": 58
            },
            {
              "date": "27 fév",
              "value": 58
            },
            {
              "date": "6 mars",
              "value": 57
            },
            {
              "date": "13 mars",
              "value": 57
            },
            {
              "date": "20 mars",
              "value": 56
            },
            {
              "date": "27 mars",
              "value": 56
            },
            {
              "date": "3 avr",
              "value": 56
            },
            {
              "date": "10 avr",
              "value": 55
            },
            {
              "date": "17 avr",
              "value": 55
            },
            {
              "date": "24 avr",
              "value": 55
            },
            {
              "date": "1 mai",
              "value": 54
            },
            {
              "date": "8 mai",
              "value": 54
            },
            {
              "date": "21 mai",
              "value": 54
            }
          ]
        },
        {
          "key": "hrv_night",
          "label": "HRV nocturne 30 j",
          "unit": "ms (RMSSD)",
          "current": "62",
          "trend_label": "+8 / 30 j",
          "points": [
            {
              "date": "23 avr",
              "value": 54
            },
            {
              "date": "25 avr",
              "value": 55
            },
            {
              "date": "27 avr",
              "value": 53
            },
            {
              "date": "29 avr",
              "value": 56
            },
            {
              "date": "1 mai",
              "value": 57
            },
            {
              "date": "3 mai",
              "value": 55
            },
            {
              "date": "5 mai",
              "value": 58
            },
            {
              "date": "7 mai",
              "value": 59
            },
            {
              "date": "9 mai",
              "value": 57
            },
            {
              "date": "11 mai",
              "value": 60
            },
            {
              "date": "13 mai",
              "value": 61
            },
            {
              "date": "15 mai",
              "value": 59
            },
            {
              "date": "17 mai",
              "value": 61
            },
            {
              "date": "19 mai",
              "value": 63
            },
            {
              "date": "21 mai",
              "value": 62
            }
          ]
        },
        {
          "key": "vo2_zone",
          "label": "Zone training Z2 30 j",
          "unit": "min/sem",
          "current": "180",
          "trend_label": "+30 vs cible",
          "points": [
            {
              "date": "30 avr",
              "value": 130
            },
            {
              "date": "7 mai",
              "value": 150
            },
            {
              "date": "14 mai",
              "value": 170
            },
            {
              "date": "21 mai",
              "value": 180
            }
          ],
          "target": {
            "value": 150,
            "label": "cible 150 OMS"
          }
        }
      ],
      "method": [
        {
          "heading": "Source VO2max",
          "body": "Estimation Firstbeat embarquée sur Huawei Watch GT2, dérivée de la fréquence cardiaque et de la vitesse GPS pendant les courses régulières. Précision validée à ± 3,5 ml/kg/min vs spiromètre de référence (Düking 2020). Ce n'est pas un test maximal direct, mais la valeur reste cohérente comme tendance hebdomadaire."
        },
        {
          "heading": "Cible 55 ml/kg/min",
          "body": "Position visée dans les normes FRIEND (Kaminsky 2017): 55 ml/kg/min correspond au 95e percentile des hommes 35-39 ans, soit le top 5-10 % de la cohorte. Atteignable sur 6 à 9 mois avec 3 séances par semaine: 1 séance d'intervalles HIIT 4×4, 2 séances d'endurance Z2 de 60 min, à condition que le VO2max actuel soit déjà ≥ 42 ml/kg/min."
        },
        {
          "heading": "HR repos & HRV",
          "body": "HR repos mesurée pendant le sommeil profond, sur la fenêtre 03h00-05h00. HRV nocturne (RMSSD) prise comme marqueur de récupération parasympathique. La tendance reste plus parlante que la valeur absolue (Plews & Laursen 2017): viser un z-score |z| < 1 vs moyenne mobile 28 j personnelle, plutôt qu'une cible universelle."
        }
      ],
      "cross_link": {
        "label": "Voir signal Dette sommeil × HRV",
        "href": "/#sleep_hrv"
      }
    },
    "recovery": {
      "key": "recovery",
      "title": "Récupération",
      "meta": "Huawei Watch GT2 · TruSleep · 14 derniers jours",
      "hero": {
        "figure": "6 h 42",
        "unit": "moyenne 7 j",
        "delta_label": "−3 h 20 sous cible 7 h sur la semaine",
        "status_label": "Dérive notable",
        "status_off": true
      },
      "trajectory": {
        "x_label": "14 jours",
        "y_unit": "min",
        "y_min": 240,
        "y_max": 540,
        "points": [
          {
            "date": "9 mai",
            "value": 425
          },
          {
            "date": "10 mai",
            "value": 390
          },
          {
            "date": "11 mai",
            "value": 360
          },
          {
            "date": "12 mai",
            "value": 445
          },
          {
            "date": "13 mai",
            "value": 480
          },
          {
            "date": "14 mai",
            "value": 320
          },
          {
            "date": "15 mai",
            "value": 410
          },
          {
            "date": "16 mai",
            "value": 395
          },
          {
            "date": "17 mai",
            "value": 370
          },
          {
            "date": "18 mai",
            "value": 460
          },
          {
            "date": "19 mai",
            "value": 340
          },
          {
            "date": "20 mai",
            "value": 395
          },
          {
            "date": "21 mai",
            "value": 430
          },
          {
            "date": "22 mai",
            "value": 402
          }
        ],
        "target": {
          "value": 420,
          "label": "cible 7 h"
        },
        "tolerance": 30
      },
      "table": [
        {
          "date": "nuit 21→22 mai",
          "value": "6 h 42",
          "unit": "",
          "delta": "−28 min"
        },
        {
          "date": "nuit 20→21 mai",
          "value": "7 h 10",
          "unit": "",
          "delta": "+35 min"
        },
        {
          "date": "nuit 19→20 mai",
          "value": "6 h 35",
          "unit": "",
          "delta": "+55 min"
        },
        {
          "date": "nuit 18→19 mai",
          "value": "5 h 40",
          "unit": "",
          "delta": "−120 min",
          "off": true
        },
        {
          "date": "nuit 17→18 mai",
          "value": "7 h 40",
          "unit": "",
          "delta": "+90 min"
        },
        {
          "date": "nuit 16→17 mai",
          "value": "6 h 10",
          "unit": "",
          "delta": "−25 min"
        },
        {
          "date": "nuit 15→16 mai",
          "value": "6 h 35",
          "unit": "",
          "delta": "−15 min"
        }
      ],
      "subs": [
        {
          "key": "sleep_latency",
          "label": "Latence endormissement 14 j",
          "unit": "min",
          "current": "22",
          "trend_label": "+5 vs baseline 28 j",
          "points": [
            {
              "date": "9 mai",
              "value": 12
            },
            {
              "date": "10 mai",
              "value": 14
            },
            {
              "date": "11 mai",
              "value": 13
            },
            {
              "date": "12 mai",
              "value": 15
            },
            {
              "date": "13 mai",
              "value": 14
            },
            {
              "date": "14 mai",
              "value": 17
            },
            {
              "date": "15 mai",
              "value": 16
            },
            {
              "date": "16 mai",
              "value": 18
            },
            {
              "date": "17 mai",
              "value": 17
            },
            {
              "date": "18 mai",
              "value": 19
            },
            {
              "date": "19 mai",
              "value": 20
            },
            {
              "date": "20 mai",
              "value": 19
            },
            {
              "date": "21 mai",
              "value": 21
            },
            {
              "date": "22 mai",
              "value": 22
            }
          ],
          "ambre": true
        },
        {
          "key": "hrv_night",
          "label": "HRV nocturne (PPG) 14 j",
          "unit": "ms RMSSD",
          "current": "48",
          "trend_label": "z = −1,2 vs perso",
          "points": [
            {
              "date": "9 mai",
              "value": 58
            },
            {
              "date": "10 mai",
              "value": 56
            },
            {
              "date": "11 mai",
              "value": 57
            },
            {
              "date": "12 mai",
              "value": 54
            },
            {
              "date": "13 mai",
              "value": 55
            },
            {
              "date": "14 mai",
              "value": 52
            },
            {
              "date": "15 mai",
              "value": 53
            },
            {
              "date": "16 mai",
              "value": 51
            },
            {
              "date": "17 mai",
              "value": 52
            },
            {
              "date": "18 mai",
              "value": 50
            },
            {
              "date": "19 mai",
              "value": 49
            },
            {
              "date": "20 mai",
              "value": 51
            },
            {
              "date": "21 mai",
              "value": 49
            },
            {
              "date": "22 mai",
              "value": 48
            }
          ],
          "ambre": true
        }
      ],
      "method": [
        {
          "heading": "Source",
          "body": "Huawei Watch GT2 TruSleep (PPG et accéléromètre). Stades détectés: éveil, léger, profond, REM. Précision sommeil total ±25 min vs polysomnographie (Chinoy 2021). HRV mesurée pendant sommeil profond, fenêtre 03h-05h."
        },
        {
          "heading": "Cible 7-8 h",
          "body": "Consensus NSF 2015 et AASM 2015 pour adultes 26-64 ans. En dessous de 6 h sur 7 nuits consécutives: dégradation cognitive mesurable (Van Dongen 2003), augmentation cortisol matinal, baisse sensibilité insuline."
        },
        {
          "heading": "Lecture HRV en récupération",
          "body": "Tendance plus informative que valeur absolue. Méthode Plews et Laursen 2017: alerter quand z-score |z| > 1 vs moyenne 28 j personnelle, persistant 3 nuits. HRV PPG (Huawei) sous-estime RMSSD de 15-20 % vs ECG mais reste fiable en tendance intra-individu."
        },
        {
          "heading": "Pourquoi ce n'est pas en rouge",
          "body": "Politique cockpit (PRODUCT.md): pas d'alarme sur métrique journalière. La dérive notable signale qu'une intervention structurelle (heure de coucher, lumière bleue, caféine après 14h) mérite arbitrage, pas qu'un seuil critique est franchi cette nuit."
        }
      ],
      "cross_link": {
        "label": "Voir signal Dette sommeil × HRV",
        "href": "/#sleep_hrv"
      }
    }
  }
}$$::jsonb)
on conflict (snapshot_date) do update set payload = excluded.payload;
