import type { CockpitSnapshot } from "./types";

// Frozen snapshot mirroring the static mockup (mockup/index.html), used as
// fallback when Supabase env vars are not configured. Lets the app run on
// `next dev` with zero setup.

export const MOCK_SNAPSHOT: CockpitSnapshot = {
  today: "2026-05-22",
  hero: {
    status: "conforme",
    statusLabel: "Conforme",
    current_kg: 83.9,
    ideal_kg: 83.6,
    delta_kg: 0.3,
    tolerance_kg: 0.8,
    start_date: "2026-04-14",
    today_week: 5.4,
    range: { kg_min: 75, kg_max: 87, week_min: 0, week_max: 52 },
    real_points: [
      { week: 0,   kg: 86.3 },
      { week: 1.0, kg: 85.9 },
      { week: 2.0, kg: 85.5 },
      { week: 3.0, kg: 85.3 },
      { week: 4.0, kg: 85.0 },
      { week: 4.7, kg: 84.4 },
      { week: 5.0, kg: 84.3 },
      { week: 5.4, kg: 83.9 },
    ],
    eta_75kg: "2027-02-18",
  },
  wegovy: {
    day_since_start: 38,
    current_dose_mg: 0.5,
    step_index: 2,
    ladder: [
      { dose_mg: 0.25, status: "done" },
      { dose_mg: 0.5,  status: "current" },
      { dose_mg: 1.0,  status: "upcoming" },
      { dose_mg: 1.7,  status: "upcoming" },
      { dose_mg: 2.4,  status: "upcoming" },
    ],
    next_dose_mg: 1.0,
    next_in_weeks: 2,
  },
  signals: [
    {
      id: "tdee",
      title: "TDEE apparent",
      sub: "28 j · coeff 6 500 (Wegovy) · biais log ~20 %",
      value: "2 270",
      unit: "± 180 kcal",
      status: "ok",
      status_label: "on track",
      spark: {
        kind: "line",
        color: "sage",
        points: [[2,14],[14,16],[26,12],[38,14],[50,11],[62,13],[78,12]],
      },
    },
    {
      id: "protein",
      title: "Protéines / LBM",
      sub: "zone adéquate 2,0–2,4 · jours train −0,3 = risque sarcopénie",
      value: "1,9",
      unit: "g/kg LBM",
      status: "watch",
      status_label: "à surveiller",
      spark: {
        kind: "bars",
        color: "ambre",
        values: [16, 18, 8, 17, 19, 9, 16, 18, 10, 17, 19, 9, 17],
        dim_indices: [2, 5, 8, 11],
      },
    },
    {
      id: "alcohol",
      title: "Alcool",
      sub: "CCSA 2023 · zone ambre 7–14 u/sem · stable vs baseline 84 j",
      value: "9",
      unit: "u/sem",
      status: "watch",
      status_label: "zone ambre",
      spark: {
        kind: "line",
        color: "ambre",
        points: [[2,12],[14,14],[26,11],[38,13],[50,12],[62,13],[78,12]],
      },
    },
    {
      id: "sleep_hrv",
      title: "Dette sommeil × HRV",
      sub: "z = −1,2 vs perso 28 j · HRV PPG trend only",
      value: "−3 h 20",
      unit: "/ 7 j",
      status: "watch",
      status_label: "à surveiller",
      spark: {
        kind: "line",
        color: "ambre",
        points: [[2,8],[14,10],[26,12],[38,13],[50,15],[62,17],[78,18]],
      },
    },
    {
      id: "wegovy_response",
      title: "Réponse Wegovy",
      sub: "−2,4 kg réel vs −2,2 prédit STEP-1 W5,4 · z = +0,1",
      value: "+0,1",
      unit: "z STEP-1",
      status: "ok",
      status_label: "sur trajectoire",
      spark: {
        kind: "line",
        color: "sage",
        end_dot: true,
        points: [[2,18],[14,17],[26,15],[38,13],[50,11],[62,9],[78,7]],
      },
    },
  ],
  bio_age: {
    composite: 33,
    chrono: 35,
    delta_vs_chrono: -2,
    subages: [
      { key: "cardio",       label: "Cardio",      value: 28 },
      { key: "blood",        label: "Sang",        value: 34 },
      { key: "composition",  label: "Composition", value: 36 },
      { key: "skeleton",     label: "Squelette",   value: 36 },
    ],
    trajectory_12m: [
      { month: "MAI '25", value: 36.0 },
      { month: "JUIL",    value: 35.7 },
      { month: "SEPT",    value: 35.2 },
      { month: "NOV",     value: 35.0 },
      { month: "JAN",     value: 34.5 },
      { month: "MAR",     value: 34.0 },
      { month: "MAI '26", value: 33.0 },
    ],
  },
  pillars: [
    {
      key: "composition",
      label: "Composition",
      meta: "21 avr",
      figure: "24,3",
      unit: "% MG",
      chart: {
        kind: "area",
        target_label: "cible 16",
        target_y: 72,
        points: [[8,12],[50,22],[92,36],[134,48],[176,56],[192,60]],
      },
    },
    {
      key: "activity",
      label: "Activité",
      meta: "auj.",
      figure: "8 247",
      unit: "pas",
      chart: {
        kind: "bars",
        target_label: "10 k",
        target_y: 18,
        values: [56, 64, 46, 66, 40, 58, 44],
        dim_indices: [4, 6],
      },
    },
    {
      key: "cardio",
      label: "Cardio",
      meta: "12 sem",
      figure: "46",
      unit: "ml/kg",
      chart: {
        kind: "area",
        target_label: "cible 55",
        target_y: 10,
        points: [[8,60],[38,56],[68,48],[98,40],[128,32],[158,26],[192,22]],
      },
    },
    {
      key: "recovery",
      label: "Récupération",
      meta: "7 j",
      figure: "6 h 42",
      unit: "moy.",
      chart: {
        kind: "bars",
        target_band: { y: 14, h: 14 },
        values: [36, 48, 28, 52, 40, 32, 40],
        ambre_indices: [0, 2, 4, 5, 6],
      },
    },
  ],
};
