import type { PillarDetail } from "../types";

export const CARDIO_DETAIL: PillarDetail = {
  key: "cardio",
  title: "Cardio",
  meta: "Huawei Watch GT2 · estimation Firstbeat",
  hero: {
    figure: "46",
    unit: "ml/kg/min",
    delta_label: "+5 vs février 2026 (3 mois)",
    status_label: "Conforme",
    status_off: false,
  },
  trajectory: {
    x_label: "12 semaines",
    y_unit: "ml/kg/min",
    y_min: 38,
    y_max: 58,
    points: [
      { date: "26 fév", value: 41 },
      { date: "5 mars", value: 41 },
      { date: "12 mars", value: 42 },
      { date: "19 mars", value: 42 },
      { date: "26 mars", value: 43 },
      { date: "2 avr", value: 43 },
      { date: "9 avr", value: 44 },
      { date: "16 avr", value: 44 },
      { date: "23 avr", value: 45 },
      { date: "30 avr", value: 45 },
      { date: "7 mai", value: 46 },
      { date: "21 mai", value: 46 },
    ],
    ideal: [
      { date: "26 fév", value: 42.0 },
      { date: "5 mars", value: 42.7 },
      { date: "12 mars", value: 43.5 },
      { date: "19 mars", value: 44.2 },
      { date: "26 mars", value: 44.9 },
      { date: "2 avr", value: 45.6 },
      { date: "9 avr", value: 46.4 },
      { date: "16 avr", value: 47.1 },
      { date: "23 avr", value: 47.8 },
      { date: "30 avr", value: 48.5 },
      { date: "7 mai", value: 49.3 },
      { date: "21 mai", value: 50.0 },
    ],
    target: { value: 55, label: "cible 55 (top 5-10 % cohorte 35-40)" },
    tolerance: 2,
  },
  table: [
    { date: "21 mai 2026", value: "46", unit: "ml/kg", delta: "+1" },
    { date: "14 mai 2026", value: "45", unit: "ml/kg", delta: "+0" },
    { date: "7 mai 2026", value: "45", unit: "ml/kg", delta: "+1" },
    { date: "30 avr 2026", value: "44", unit: "ml/kg", delta: "+0" },
    { date: "23 avr 2026", value: "44", unit: "ml/kg", delta: "+1" },
    { date: "16 avr 2026", value: "43", unit: "ml/kg", delta: "+1" },
  ],
  subs: [
    {
      key: "hr_rest",
      label: "HR repos 90 j",
      unit: "bpm",
      current: "54",
      trend_label: "−4 / 90 j",
      points: [
        { date: "20 fév", value: 58 },
        { date: "27 fév", value: 58 },
        { date: "6 mars", value: 57 },
        { date: "13 mars", value: 57 },
        { date: "20 mars", value: 56 },
        { date: "27 mars", value: 56 },
        { date: "3 avr", value: 56 },
        { date: "10 avr", value: 55 },
        { date: "17 avr", value: 55 },
        { date: "24 avr", value: 55 },
        { date: "1 mai", value: 54 },
        { date: "8 mai", value: 54 },
        { date: "21 mai", value: 54 },
      ],
    },
    {
      key: "hrv_night",
      label: "HRV nocturne 30 j",
      unit: "ms (RMSSD)",
      current: "62",
      trend_label: "+8 / 30 j",
      points: [
        { date: "23 avr", value: 54 },
        { date: "25 avr", value: 55 },
        { date: "27 avr", value: 53 },
        { date: "29 avr", value: 56 },
        { date: "1 mai", value: 57 },
        { date: "3 mai", value: 55 },
        { date: "5 mai", value: 58 },
        { date: "7 mai", value: 59 },
        { date: "9 mai", value: 57 },
        { date: "11 mai", value: 60 },
        { date: "13 mai", value: 61 },
        { date: "15 mai", value: 59 },
        { date: "17 mai", value: 61 },
        { date: "19 mai", value: 63 },
        { date: "21 mai", value: 62 },
      ],
    },
    {
      key: "vo2_zone",
      label: "Zone training Z2 30 j",
      unit: "min/sem",
      current: "180",
      trend_label: "+30 vs cible",
      points: [
        { date: "30 avr", value: 130 },
        { date: "7 mai", value: 150 },
        { date: "14 mai", value: 170 },
        { date: "21 mai", value: 180 },
      ],
      target: { value: 150, label: "cible 150 OMS" },
    },
  ],
  method: [
    {
      heading: "Source VO2max",
      body: "Estimation Firstbeat embarquée sur Huawei Watch GT2, dérivée de la fréquence cardiaque et de la vitesse GPS pendant les courses régulières. Précision validée à ± 3,5 ml/kg/min vs spiromètre de référence (Düking 2020). Ce n'est pas un test maximal direct, mais la valeur reste cohérente comme tendance hebdomadaire.",
    },
    {
      heading: "Cible 55 ml/kg/min",
      body: "Position visée dans les normes FRIEND (Kaminsky 2017): 55 ml/kg/min correspond au 95e percentile des hommes 35-39 ans, soit le top 5-10 % de la cohorte. Atteignable sur 6 à 9 mois avec 3 séances par semaine: 1 séance d'intervalles HIIT 4×4, 2 séances d'endurance Z2 de 60 min, à condition que le VO2max actuel soit déjà ≥ 42 ml/kg/min.",
    },
    {
      heading: "HR repos & HRV",
      body: "HR repos mesurée pendant le sommeil profond, sur la fenêtre 03h00-05h00. HRV nocturne (RMSSD) prise comme marqueur de récupération parasympathique. La tendance reste plus parlante que la valeur absolue (Plews & Laursen 2017): viser un z-score |z| < 1 vs moyenne mobile 28 j personnelle, plutôt qu'une cible universelle.",
    },
  ],
  cross_link: { label: "Voir signal Dette sommeil × HRV", href: "/#sleep_hrv" },
};
