import type { PillarDetail } from "../types";

export const RECOVERY_DETAIL: PillarDetail = {
  key: "recovery",
  title: "Récupération",
  meta: "Huawei Watch GT2 · TruSleep · 14 derniers jours",
  hero: {
    figure: "6 h 42",
    unit: "moyenne 7 j",
    delta_label: "−3 h 20 sous cible 7 h sur la semaine",
    status_label: "Dérive notable",
    status_off: true,
  },
  trajectory: {
    x_label: "14 jours",
    y_unit: "min",
    y_min: 240,
    y_max: 540,
    points: [
      { date: "9 mai", value: 425 },
      { date: "10 mai", value: 390 },
      { date: "11 mai", value: 360 },
      { date: "12 mai", value: 445 },
      { date: "13 mai", value: 480 },
      { date: "14 mai", value: 320 },
      { date: "15 mai", value: 410 },
      { date: "16 mai", value: 395 },
      { date: "17 mai", value: 370 },
      { date: "18 mai", value: 460 },
      { date: "19 mai", value: 340 },
      { date: "20 mai", value: 395 },
      { date: "21 mai", value: 430 },
      { date: "22 mai", value: 402 },
    ],
    target: { value: 420, label: "cible 7 h" },
    tolerance: 30,
  },
  table: [
    { date: "nuit 21→22 mai", value: "6 h 42", unit: "", delta: "−28 min" },
    { date: "nuit 20→21 mai", value: "7 h 10", unit: "", delta: "+35 min" },
    { date: "nuit 19→20 mai", value: "6 h 35", unit: "", delta: "+55 min" },
    { date: "nuit 18→19 mai", value: "5 h 40", unit: "", delta: "−120 min", off: true },
    { date: "nuit 17→18 mai", value: "7 h 40", unit: "", delta: "+90 min" },
    { date: "nuit 16→17 mai", value: "6 h 10", unit: "", delta: "−25 min" },
    { date: "nuit 15→16 mai", value: "6 h 35", unit: "", delta: "−15 min" },
  ],
  subs: [
    {
      key: "sleep_latency",
      label: "Latence endormissement 14 j",
      unit: "min",
      current: "22",
      trend_label: "+5 vs baseline 28 j",
      points: [
        { date: "9 mai", value: 12 },
        { date: "10 mai", value: 14 },
        { date: "11 mai", value: 13 },
        { date: "12 mai", value: 15 },
        { date: "13 mai", value: 14 },
        { date: "14 mai", value: 17 },
        { date: "15 mai", value: 16 },
        { date: "16 mai", value: 18 },
        { date: "17 mai", value: 17 },
        { date: "18 mai", value: 19 },
        { date: "19 mai", value: 20 },
        { date: "20 mai", value: 19 },
        { date: "21 mai", value: 21 },
        { date: "22 mai", value: 22 },
      ],
      ambre: true,
    },
    {
      key: "hrv_night",
      label: "HRV nocturne (PPG) 14 j",
      unit: "ms RMSSD",
      current: "48",
      trend_label: "z = −1,2 vs perso",
      points: [
        { date: "9 mai", value: 58 },
        { date: "10 mai", value: 56 },
        { date: "11 mai", value: 57 },
        { date: "12 mai", value: 54 },
        { date: "13 mai", value: 55 },
        { date: "14 mai", value: 52 },
        { date: "15 mai", value: 53 },
        { date: "16 mai", value: 51 },
        { date: "17 mai", value: 52 },
        { date: "18 mai", value: 50 },
        { date: "19 mai", value: 49 },
        { date: "20 mai", value: 51 },
        { date: "21 mai", value: 49 },
        { date: "22 mai", value: 48 },
      ],
      ambre: true,
    },
  ],
  method: [
    {
      heading: "Source",
      body: "Huawei Watch GT2 TruSleep (PPG et accéléromètre). Stades détectés: éveil, léger, profond, REM. Précision sommeil total ±25 min vs polysomnographie (Chinoy 2021). HRV mesurée pendant sommeil profond, fenêtre 03h-05h.",
    },
    {
      heading: "Cible 7-8 h",
      body: "Consensus NSF 2015 et AASM 2015 pour adultes 26-64 ans. En dessous de 6 h sur 7 nuits consécutives: dégradation cognitive mesurable (Van Dongen 2003), augmentation cortisol matinal, baisse sensibilité insuline.",
    },
    {
      heading: "Lecture HRV en récupération",
      body: "Tendance plus informative que valeur absolue. Méthode Plews et Laursen 2017: alerter quand z-score |z| > 1 vs moyenne 28 j personnelle, persistant 3 nuits. HRV PPG (Huawei) sous-estime RMSSD de 15-20 % vs ECG mais reste fiable en tendance intra-individu.",
    },
    {
      heading: "Pourquoi ce n'est pas en rouge",
      body: "Politique cockpit (PRODUCT.md): pas d'alarme sur métrique journalière. La dérive notable signale qu'une intervention structurelle (heure de coucher, lumière bleue, caféine après 14h) mérite arbitrage, pas qu'un seuil critique est franchi cette nuit.",
    },
  ],
  cross_link: { label: "Voir signal Dette sommeil × HRV", href: "/#sleep_hrv" },
};
