// Render supabase/seed.sql from the live MOCK_SNAPSHOT so the seed always
// matches the in-app fallback values byte-for-byte.
import { writeFileSync } from "fs";
import { MOCK_SNAPSHOT } from "../lib/mock-data.ts";

const json = JSON.stringify(MOCK_SNAPSHOT, null, 2);
const sql = `-- AUTO-GENERATED by scripts/build-seed.mjs from lib/mock-data.ts.
-- Re-run \`node scripts/build-seed.mjs\` after editing the mock.

insert into public.cockpit_snapshot (snapshot_date, payload) values
('${MOCK_SNAPSHOT.today}', $$${json}$$::jsonb)
on conflict (snapshot_date) do update set payload = excluded.payload;
`;

writeFileSync("supabase/seed.sql", sql);
console.log("wrote supabase/seed.sql");
